In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"RollNo": [101, 102, 103, 104],"Name": ["Ram", "Sam", "Joy", "Raj"],"City": ["Pune", "Mumbai", "Nashik", "Bangalore"]})

In [3]:
df

   RollNo Name       City
0     101  Ram       Pune
1     102  Sam     Mumbai
2     103  Joy     Nashik
3     104  Raj  Bangalore

In [4]:
df.head()

   RollNo Name       City
0     101  Ram       Pune
1     102  Sam     Mumbai
2     103  Joy     Nashik
3     104  Raj  Bangalore

In [5]:
df.tail()

   RollNo Name       City
0     101  Ram       Pune
1     102  Sam     Mumbai
2     103  Joy     Nashik
3     104  Raj  Bangalore

In [6]:
df.shape

(4, 3)

In [7]:
df.columns

Index(['RollNo', 'Name', 'City'], dtype='object')

In [8]:
df["Name"]

0    Ram
1    Sam
2    Joy
3    Raj
Name: Name, dtype: object

In [9]:
df[["RollNo", "City"]]

   RollNo       City
0     101       Pune
1     102     Mumbai
2     103     Nashik
3     104  Bangalore

In [10]:
df.loc[0]

RollNo     101
Name       Ram
City      Pune
Name: 0, dtype: object

In [11]:
df.loc[1:3]

   RollNo Name       City
1     102  Sam     Mumbai
2     103  Joy     Nashik
3     104  Raj  Bangalore

In [12]:
df.head(2)

   RollNo Name    City
0     101  Ram    Pune
1     102  Sam  Mumbai

In [13]:
df.dtypes

RollNo     int64
Name      object
City      object
dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RollNo  4 non-null      int64
 1   Name    4 non-null      object
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [15]:
df.describe()

           RollNo
count    4.000000
mean   102.500000
std      1.290994
min    101.000000
25%    101.750000
50%    102.500000
75%    103.250000
max    104.000000

In [16]:
df.loc[0:2]

   RollNo Name    City
0     101  Ram    Pune
1     102  Sam  Mumbai
2     103  Joy  Nashik

In [17]:
df.iloc[0]

RollNo     101
Name       Ram
City      Pune
Name: 0, dtype: object

In [18]:
df.loc[[0]]

   RollNo Name  City
0     101  Ram  Pune

In [23]:
     df = pd.read_csv("titanic.csv")

In [24]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [26]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [27]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [28]:
x= df.Math_Score.mean()

AttributeError: 'DataFrame' object has no attribute 'Math_Score'

In [29]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [30]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [32]:
df['Age'].mean()

np.float64(29.69911764705882)

In [33]:
df['Fare'].mean()

np.float64(32.204207968574636)

In [34]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [35]:
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [36]:
df.shape

(891, 12)

In [37]:
df[df['Survived']==1]['Age'].mean()

np.float64(28.343689655172415)